# Generated by Django 4.2.9 on 2024-01-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("customer", models.CharField(default="", max_length=255)),
                (
                    "contact",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, null=True
                    ),
                ),
                ("phone_number", models.BigIntegerField(blank=True, null=True)),
                ("alt_phone_number", models.BigIntegerField(blank=True, null=True)),
                ("total", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_price", models.FloatField(default=0)),
                (
                    "product_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("product_is_delete", models.BooleanField(default=False)),
                (
                    "product_warranty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1 YEAR", "1 YEAR"),
                            ("2 YEAR", "2 YEAR"),
                            ("No warranties", "No warranties"),
                        ],
                        default="No warranties",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("months", models.IntegerField()),
                (
                    "service_period",
                    models.IntegerField(
                        help_text="Enter number of mounth in which you want to give services."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField()),
                ("generate_date", models.DateField(auto_now_add=True)),
                ("complate_date", models.DateField()),
                ("is_complate", models.BooleanField(default=False)),
                ("service_number", models.IntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_service",
                        to="invoice.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=1)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice",
                        to="invoice.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invoice.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoice.subscription",
            ),
        ),
        migrations.CreateModel(
            name="Complain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("description", models.TextField()),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoice.invoice",
                    ),
                ),
            ],
        ),
    ]
